apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: musicstore
resources:
  - namespace.yaml
  - secret-postgres.yaml
  - configmap-app.yaml
  - postgres.yaml
  - apache.yaml
  - ingress.yaml
