apiVersion: v1
kind: Secret
metadata:
  name: musicstore-postgres-secret
  namespace: musicstore
type: Opaque
stringData:
  postgres_db: musicstore
  postgres_user: musicstore
  postgres_password: change-me-strong-password
